runtime: go
api_version: go1

handlers:
  - url: /
    static_files: client/index.html
    upload: client/index.html

  - url: /data/
    static_dir: data

  - url: /(.*)$
    static_files: client/\1
    upload: client/.*

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^client/src/typings/.*$
  - ^client/src/.*\.ts$
  - ^client/src/.*\.json$
  - ^client/src/webpack\.config\.js$
  - ^client/src/node_modules/.*$
